name: Bug report
description: Report a bug
labels: ["bug"]
assignees: ["zbhavyai"]

body:
  - type: textarea
    id: description
    validations:
      required: true
    attributes:
      label: Describe the bug
      description: Describe the issue you are experiencing. Tell us what you were trying to do and what happened. Provide a clear and concise description of what the problem is.

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: Describe the expected behavior clearly and concisely.

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: Describe the actual behavior clearly and concisely.

  - type: textarea
    id: steps
    attributes:
      label: How to reproduce
      description: Provide exact steps or commands to reproduce the bug. Link a reproducer if applicable / possible.
      placeholder: |
        Steps to reproduce the behavior:
        1.
        2.
        3.

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        OS details, container engine, and project version info.
        Prefer `fastfetch` output and/or relevant excerpts from `/etc/os-release`.
      placeholder: |
        OS: Fedora Workstation 42
        Kernel: 6.15.9
        Container Engine: Podman 5.5.2
        Java: Temurin 21.0.7
        Project version/commit: `d2c8401`

  - type: textarea
    id: additional
    attributes:
      label: Additional information
      description: Anything else relevant can go here.
